language: python
python:
  - "2.7"

# command to install dependencies

before_install:
  - cd tests 
install:
  pip install --user -r requirements.txt



script: python hubro_backend_unit_tests.py
  
 #Her må vi liste opp alle unit tester og andre tester som vi vil at Travis skal kjøre ved build
 #Kan kanskje dette automatiseres? Altså at tester legges automatisk til her?


