language: python
python:
  - '3.5'
  - '3.4'
  - '2.7'
matrix:
  include:
    - python: '3.5'
      env: EXTRA_TESTS=true
    - python: '3.4'
      env: EXTRA_TESTS=true
    - python: '2.7'
      env: EXTRA_TESTS=true
script:
  env $EXTRA_TESTS ./tests/* $TEST_SUITE

# command to install dependencies

before_install:
  - cd tests 
install:
  pip install pyvirtualdisplay;
  pip install selenium;
  pip install SQLAlchemy;

script:
  #python TEST_hubro_backend_unit.py;
  #python TEST_owlbrainScheduler.py;



